dihedral_name = "dih-{resid:03d}-{angid:02d}"
dihedral_def_from_atoms = "{name}: TORSION ATOMS={a1},{a2},{a3},{a4}"
distance_name = "dis-{atomid1:05d}-{atomid2:05d}"
distance_def_from_atoms = "{name}: DISTANCE ATOMS={a1},{a2}"
print_def = "PRINT STRIDE={stride} ARG={arg} FILE={file}"
restraint_def = "{name}: RESTRAINT ARG={arg} KAPPA={kappa} AT={at}"
moving_restraint_def = "{name}: MOVINGRESTRAINT ARG={arg} STEP0={step0} AT0={at0} KAPPA0={kappa0} STEP1={step1} AT1={at1} KAPPA1={kappa1} STEP2={step2} AT2={at2} KAPPA2={kappa2}"
restraint_prefix = "res"